# Generated by Django 4.0.4 on 2022-05-07 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=5)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('won', models.BooleanField()),
                ('score', models.SmallIntegerField(default=0)),
                ('player', models.ForeignKey(default='guest', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
